src/mac_command.sh: mute nvmtool and ifdtool when setting MAC
Signed-off-by: Michał Kopeć <michal.kopec@3mdeb.com>

diff --git a/dcu b/dcu
--- a/dcu
+++ b/dcu
@@ -1,5 +1,5 @@
 #!/usr/bin/env bash
-# This script was generated by bashly 1.2.1 (https://bashly.dannyb.co)
+# This script was generated by bashly 1.1.10 (https://bashly.dannyb.co)
 # Modifying it manually is not recommended
 
 # :wrapper.bash3_bouncer
@@ -17,7 +17,15 @@ version_command() {
 
 # :command.usage
 dcu_usage() {
-  printf "dcu - Dasharo Configuration Utility\n\n"
+  if [[ -n $long_usage ]]; then
+    printf "dcu - Dasharo Configuration Utility\n"
+    echo
+
+  else
+    printf "dcu - Dasharo Configuration Utility\n"
+    echo
+
+  fi
 
   printf "%s\n" "Usage:"
   printf "  dcu COMMAND\n"
@@ -57,7 +65,16 @@ dcu_usage() {
 
 # :command.usage
 dcu_mac_usage() {
-  printf "dcu mac - Get/set MAC address in a firmware image\n\n"
+  if [[ -n $long_usage ]]; then
+    printf "dcu mac - Get/set MAC address in a firmware image\n"
+    echo
+
+  else
+    printf "dcu mac - Get/set MAC address in a firmware image\n"
+    echo
+
+  fi
+
   printf "Alias: m\n"
   echo
 
@@ -100,7 +117,16 @@ dcu_mac_usage() {
 
 # :command.usage
 dcu_smbios_usage() {
-  printf "dcu smbios - Edit SMBIOS data in a firmware image\n\n"
+  if [[ -n $long_usage ]]; then
+    printf "dcu smbios - Edit SMBIOS data in a firmware image\n"
+    echo
+
+  else
+    printf "dcu smbios - Edit SMBIOS data in a firmware image\n"
+    echo
+
+  fi
+
   printf "Alias: s\n"
   echo
 
@@ -149,7 +175,16 @@ dcu_smbios_usage() {
 
 # :command.usage
 dcu_logo_usage() {
-  printf "dcu logo - Insert custom logo boot splash into firmware image\n\n"
+  if [[ -n $long_usage ]]; then
+    printf "dcu logo - Insert custom logo boot splash into firmware image\n"
+    echo
+
+  else
+    printf "dcu logo - Insert custom logo boot splash into firmware image\n"
+    echo
+
+  fi
+
   printf "Alias: l\n"
   echo
 
@@ -191,7 +226,16 @@ dcu_logo_usage() {
 
 # :command.usage
 dcu_variable_usage() {
-  printf "dcu variable - Edit Dasharo configuration variables\n\n"
+  if [[ -n $long_usage ]]; then
+    printf "dcu variable - Edit Dasharo configuration variables\n"
+    echo
+
+  else
+    printf "dcu variable - Edit Dasharo configuration variables\n"
+    echo
+
+  fi
+
   printf "Alias: v\n"
   echo
 
@@ -255,7 +299,7 @@ dcu_variable_usage() {
 # :command.normalize_input
 # :command.normalize_input_function
 normalize_input() {
-  local arg passthru flags
+  local arg flags passthru
   passthru=false
 
   while [[ $# -gt 0 ]]; do
@@ -353,8 +397,8 @@ dcu_mac_command() {
       fi
     fi
 
-    "${NVMTOOL}" "$GBE_FLASHREGION_FILENAME" setmac "${_mac}" || { echo "Failed to write MAC" ; return 22; }
-    "${IFDTOOL}" -i gbe:"$GBE_FLASHREGION_FILENAME" "${DASHARO_ROM}" || { echo "Failed to insert gbe to the binary" ; return 21; }
+    "${NVMTOOL}" "$GBE_FLASHREGION_FILENAME" setmac "${_mac}" &> /dev/null || { echo "Failed to write MAC" ; return 22; }
+    "${IFDTOOL}" -i gbe:"$GBE_FLASHREGION_FILENAME" "${DASHARO_ROM}" &> /dev/null || { echo "Failed to insert gbe to the binary" ; return 21; }
     echo "Moving ${DASHARO_ROM}.new to ${DASHARO_ROM}"
     mv "${DASHARO_ROM}.new" "${DASHARO_ROM}" -f
     echo "Success"
@@ -367,7 +411,7 @@ dcu_mac_command() {
   }
 
   init() {
-    "${IFDTOOL}" -x "${DASHARO_ROM}" > /dev/null 2>&1 || { echo "Failed to extract sections"; }
+    "${IFDTOOL}" -x "${DASHARO_ROM}" &> /dev/null || { echo "Failed to extract sections"; }
     if [[ ! -f "$GBE_FLASHREGION_FILENAME" ]]; then
       echo "Managing the MAC address in this binary is currently not supported"
       return 21
@@ -961,7 +1005,6 @@ dcu_mac_parse_requirements() {
   # :command.required_args_filter
   if [[ -z ${args['dasharo_rom_file']+x} ]]; then
     printf "missing required argument: DASHARO_ROM_FILE\nusage: dcu mac DASHARO_ROM_FILE [OPTIONS]\n" >&2
-
     exit 1
   fi
 
@@ -1045,7 +1088,6 @@ dcu_smbios_parse_requirements() {
   # :command.required_args_filter
   if [[ -z ${args['dasharo_rom_file']+x} ]]; then
     printf "missing required argument: DASHARO_ROM_FILE\nusage: dcu smbios DASHARO_ROM_FILE [OPTIONS]\n" >&2
-
     exit 1
   fi
 
@@ -1115,7 +1157,6 @@ dcu_logo_parse_requirements() {
   # :command.required_args_filter
   if [[ -z ${args['dasharo_rom_file']+x} ]]; then
     printf "missing required argument: DASHARO_ROM_FILE\nusage: dcu logo DASHARO_ROM_FILE [OPTIONS]\n" >&2
-
     exit 1
   fi
 
@@ -1235,7 +1276,6 @@ dcu_variable_parse_requirements() {
   # :command.required_args_filter
   if [[ -z ${args['dasharo_rom_file']+x} ]]; then
     printf "missing required argument: DASHARO_ROM_FILE\nusage: dcu variable DASHARO_ROM_FILE [OPTIONS]\n" >&2
-
     exit 1
   fi
 
