src/mac_command,README: Add proper return codes
Signed-off-by: Filip Gołaś <filip.golas@3mdeb.com>

diff --git a/dcu b/dcu
--- a/dcu
+++ b/dcu
@@ -340,7 +340,6 @@ dcu_mac_command() {
 
   set_mac() {
     local _mac="$1"
-
     if "${NVMTOOL}" "$GBE_FLASHREGION_FILENAME" copy 0; then
       echo "Copying region 0 to region 1"
     else
@@ -350,12 +349,12 @@ dcu_mac_command() {
       else
         echo "Failed to copy region 1 to region 0"
         echo "Both regions are invalid, aborting"
-        return 1
+        return 23
       fi
     fi
 
-    "${NVMTOOL}" "$GBE_FLASHREGION_FILENAME" setmac "${_mac}" || { echo "Failed to write MAC" ; return 1; }
-    "${IFDTOOL}" -i gbe:"$GBE_FLASHREGION_FILENAME" "${DASHARO_ROM}" || { echo "Failed to insert gbe to the binary" ; return 1; }
+    "${NVMTOOL}" "$GBE_FLASHREGION_FILENAME" setmac "${_mac}" || { echo "Failed to write MAC" ; return 21; }
+    "${IFDTOOL}" -i gbe:"$GBE_FLASHREGION_FILENAME" "${DASHARO_ROM}" || { echo "Failed to insert gbe to the binary" ; return 22; }
     echo "Moving ${DASHARO_ROM}.new to ${DASHARO_ROM}"
     mv "${DASHARO_ROM}.new" "${DASHARO_ROM}" -f
     echo "Success"
@@ -363,16 +362,15 @@ dcu_mac_command() {
 
   get_mac() {
     # dump sections
-    "${IFDTOOL}" -x "${DASHARO_ROM}" > /dev/null 2>&1 || { echo "Failed to extract sections" ; return 1; }
     "${NVMTOOL}" "$GBE_FLASHREGION_FILENAME" dump
     echo "Success"
   }
 
   init() {
-    "${IFDTOOL}" -x "${DASHARO_ROM}" > /dev/null 2>&1 || { echo "Failed to extract sections" ;}
+    "${IFDTOOL}" -x "${DASHARO_ROM}" > /dev/null 2>&1 || { echo "Failed to extract sections"; }
     if [[ ! -f "$GBE_FLASHREGION_FILENAME" ]]; then
       echo "Managing the MAC address in this binary is currently not supported"
-      return 1
+      return 23
     fi
   }
 
