src/mac_command.sh: Add changing mac in rom
The operation got lost during debugging

Signed-off-by: Filip Gołaś <filip.golas@3mdeb.com>

diff --git a/dcu b/dcu
--- a/dcu
+++ b/dcu
@@ -355,6 +355,7 @@ dcu_mac_command() {
       fi
     fi
 
+    "${NVMTOOL}" "flashregion_3_gbe.bin" setmac "${_mac}" || { echo "Failed to write MAC" ; return 1; }
     "${IFDTOOL}" -i gbe:flashregion_3_gbe.bin "${DASHARO_ROM}" || { echo "Failed to insert gbe to the binary" ; return 1; }
     echo "Moving ${DASHARO_ROM}.new to ${DASHARO_ROM}"
     mv "${DASHARO_ROM}.new" "${DASHARO_ROM}"
