Add basic support for smmstoretool
Signed-off-by: Piotr Kubaj <piotr.kubaj@3mdeb.com>

diff --git a/dcu b/dcu
--- a/dcu
+++ b/dcu
@@ -1,5 +1,5 @@
 #!/usr/bin/env bash
-# This script was generated by bashly 1.0.4 (https://bashly.dannyb.co)
+# This script was generated by bashly 1.1.10 (https://bashly.dannyb.co)
 # Modifying it manually is not recommended
 
 # :wrapper.bash3_bouncer
@@ -34,8 +34,9 @@ dcu_usage() {
   echo
   # :command.usage_commands
   printf "%s\n" "Commands:"
-  printf "  %s   Edit SMBIOS data in a firmware image\n" "smbios"
-  printf "  %s   Insert custom logo boot splash into firmware image\n" "logo  "
+  printf "  %s   Edit SMBIOS data in a firmware image\n" "smbios  "
+  printf "  %s   Insert custom logo boot splash into firmware image\n" "logo    "
+  printf "  %s   Edit settings stored in SMMSTORE\n" "smmstore"
   echo
 
   # :command.long_usage
@@ -54,6 +55,7 @@ dcu_usage() {
     printf "%s\n" "Examples:"
     printf "  dcu smbios coreboot.rom -u 96bcfa1a-42b4-6717-a44c-d8bbc18cbea4 -s D07229051\n"
     printf "  dcu logo coreboot.rom -l bootsplash.bmp\n"
+    printf "  dcu smmstore coreboot.rom --get EnableWifiBt\n"
     echo
 
   fi
@@ -70,9 +72,6 @@ dcu_smbios_usage() {
     echo
 
   fi
-
-  printf "Alias: s\n"
-  echo
 
   printf "%s\n" "Usage:"
   printf "  dcu smbios DASHARO_ROM_FILE [OPTIONS]\n"
@@ -168,13 +167,80 @@ dcu_logo_usage() {
   fi
 }
 
+# :command.usage
+dcu_smmstore_usage() {
+  if [[ -n $long_usage ]]; then
+    printf "dcu smmstore - Edit settings stored in SMMSTORE\n"
+    echo
+
+  else
+    printf "dcu smmstore - Edit settings stored in SMMSTORE\n"
+    echo
+
+  fi
+
+  printf "%s\n" "Usage:"
+  printf "  dcu smmstore DASHARO_ROM_FILE [OPTIONS]\n"
+  printf "  dcu smmstore --help | -h\n"
+  echo
+
+  # :command.long_usage
+  if [[ -n $long_usage ]]; then
+    printf "%s\n" "Options:"
+
+    # :command.usage_flags
+    # :flag.usage
+    printf "  %s\n" "--get VAR"
+    printf "    Name of an SMMSTORE variable\n"
+    echo
+
+    # :flag.usage
+    printf "  %s\n" "--list"
+    printf "    List available variables\n"
+    echo
+
+    # :flag.usage
+    printf "  %s\n" "--set VAR"
+    printf "    Name of an SMMSTORE variable\n"
+    echo
+
+    # :flag.usage
+    printf "  %s\n" "--value VAL"
+    printf "    Value to set in a variable\n"
+    echo
+
+    # :command.usage_fixed_flags
+    printf "  %s\n" "--help, -h"
+    printf "    Show this help\n"
+    echo
+
+    # :command.usage_args
+    printf "%s\n" "Arguments:"
+
+    # :argument.usage
+    printf "  %s\n" "DASHARO_ROM_FILE"
+    printf "    Dasharo firmware file (e.g. coreboot.rom)\n"
+    echo
+
+    # :command.usage_examples
+    printf "%s\n" "Examples:"
+    printf "  dcu smmstore coreboot.rom --get EnableWifiBt\n"
+    echo
+
+  fi
+}
+
 # :command.normalize_input
+# :command.normalize_input_function
 normalize_input() {
-  local arg flags
+  local arg flags passthru
+  passthru=false
 
   while [[ $# -gt 0 ]]; do
     arg="$1"
-    if [[ $arg =~ ^(--[a-zA-Z0-9_\-]+)=(.+)$ ]]; then
+    if [[ $passthru == true ]]; then
+      input+=("$arg")
+    elif [[ $arg =~ ^(--[a-zA-Z0-9_\-]+)=(.+)$ ]]; then
       input+=("${BASH_REMATCH[1]}")
       input+=("${BASH_REMATCH[2]}")
     elif [[ $arg =~ ^(-[a-zA-Z0-9])=(.+)$ ]]; then
@@ -185,6 +251,9 @@ normalize_input() {
       for ((i = 0; i < ${#flags}; i++)); do
         input+=("-${flags:i:1}")
       done
+    elif [[ "$arg" == "--" ]]; then
+      passthru=true
+      input+=("$arg")
     else
       input+=("$arg")
     fi
@@ -192,12 +261,15 @@ normalize_input() {
     shift
   done
 }
+
 # :command.inspect_args
 inspect_args() {
   if ((${#args[@]})); then
     readarray -t sorted_keys < <(printf '%s\n' "${!args[@]}" | sort)
     echo args:
-    for k in "${sorted_keys[@]}"; do echo "- \${args[$k]} = ${args[$k]}"; done
+    for k in "${sorted_keys[@]}"; do
+      echo "- \${args[$k]} = ${args[$k]}"
+    done
   else
     echo args: none
   fi
@@ -215,9 +287,19 @@ inspect_args() {
     readarray -t sorted_keys < <(printf '%s\n' "${!deps[@]}" | sort)
     echo
     echo deps:
-    for k in "${sorted_keys[@]}"; do echo "- \${deps[$k]} = ${deps[$k]}"; done
+    for k in "${sorted_keys[@]}"; do
+      echo "- \${deps[$k]} = ${deps[$k]}"
+    done
   fi
 
+  if ((${#env_var_names[@]})); then
+    readarray -t sorted_names < <(printf '%s\n' "${env_var_names[@]}" | sort)
+    echo
+    echo "environment variables:"
+    for k in "${sorted_names[@]}"; do
+      echo "- \$$k = ${!k:-}"
+    done
+  fi
 }
 
 # :command.command_functions
@@ -360,6 +442,58 @@ dcu_logo_command() {
 
 }
 
+# :command.function
+dcu_smmstore_command() {
+  # src/smmstore_command.sh
+  # SPDX-FileCopyrightText: 2023 3mdeb <contact@3mdeb.com>
+  #
+  # SPDX-License-Identifier: Apache-2.0
+
+  # inspect_args
+
+  DASHARO_ROM="${args[dasharo_rom_file]}"
+  GET="${args[--get]}"
+  VALUE="${args[--value]}"
+  SET="${args[--set]}"
+
+  get_variable()
+  {
+  	${SMMSTORETOOL} ${DASHARO_ROM} get -g dasharo -n ${GET} -t bool
+  	if [ $? -neq 0 ]
+  	then
+  		echo "Error, correct passed arguments"
+  		exit 1
+  	fi
+  }
+
+  set_variable()
+  {
+  	if [ -z "${VALUE}" ]
+  	then
+  		echo "Value to set not provided, exiting" >&2
+  		exit 1
+  	fi
+  	${SMMSTORETOOL} ${DASHARO_ROM} set -g dasharo -n ${SET} -t bool -v ${VALUE}
+  	if [ $? -neq 0 ]
+  	then
+  		echo "Error, correct passed arguments" >&2
+  		exit 1
+  	fi
+  }
+
+  if [ -n "${GET}" ]
+  then
+  	get_variable
+  elif [ -n "${LIST}" ]
+  then
+  	list_variables
+  elif [ -n "${SET}" ]
+  then
+  	set_variable
+  fi
+
+}
+
 # :command.parse_requirements
 parse_requirements() {
   # :command.fixed_flags_filter
@@ -388,12 +522,7 @@ parse_requirements() {
     deps['cbfstool']="$(command -v cbfstool | head -n1)"
   else
     printf "missing dependency: cbfstool\n" >&2
-    printf "%s\n" "You can build one from source code:
-    https://github.com/Dasharo/dcu#compiling-cbfstool
-  Or download and install pre-built version with following commands:
-    sudo wget -O /usr/local/bin/cbfstool https://dl.3mdeb.com/open-source-firmware/utilities/cbfstool
-    sudo chmod +x /usr/local/bin/cbfstool
-  " >&2
+    printf "%s\n" "You can build one from source code:\n  https://github.com/Dasharo/dcu#compiling-cbfstool\nOr download and install pre-built version with following commands:\n  sudo wget -O /usr/local/bin/cbfstool https://dl.3mdeb.com/open-source-firmware/utilities/cbfstool\n  sudo chmod +x /usr/local/bin/cbfstool\n" >&2
     exit 1
   fi
 
@@ -413,13 +542,21 @@ parse_requirements() {
     exit 1
   fi
 
+  if command -v cbfstool >/dev/null 2>&1; then
+    deps['smmstoretool']="$(command -v cbfstool | head -n1)"
+  else
+    printf "missing dependency: smmstoretool\n" >&2
+    printf "%s\n" "You can build one from source code:\n  https://github.com/Dasharo/dcu#compiling-smmstoretool\nOr download and install pre-built version with following commands:\n  sudo wget -O /usr/local/bin/smmstoretool https://dl.3mdeb.com/open-source-firmware/utilities/smmstoretool\n  sudo chmod +x /usr/local/bin/smmstoretool\n" >&2
+    exit 1
+  fi
+
   # :command.command_filter
   action=${1:-}
 
   case $action in
     -*) ;;
 
-    smbios | s)
+    smbios)
       action="smbios"
       shift
       dcu_smbios_parse_requirements "$@"
@@ -430,6 +567,13 @@ parse_requirements() {
       action="logo"
       shift
       dcu_logo_parse_requirements "$@"
+      shift $#
+      ;;
+
+    smmstore)
+      action="smmstore"
+      shift
+      dcu_smmstore_parse_requirements "$@"
       shift $#
       ;;
 
@@ -499,7 +643,6 @@ dcu_smbios_parse_requirements() {
 
         # :flag.case_arg
         if [[ -n ${2+x} ]]; then
-
           args['--uuid']="$2"
           shift
           shift
@@ -514,7 +657,6 @@ dcu_smbios_parse_requirements() {
 
         # :flag.case_arg
         if [[ -n ${2+x} ]]; then
-
           args['--serial-number']="$2"
           shift
           shift
@@ -532,8 +674,8 @@ dcu_smbios_parse_requirements() {
       *)
         # :command.parse_requirements_case
         # :command.parse_requirements_case_simple
+        # :argument.case
         if [[ -z ${args['dasharo_rom_file']+x} ]]; then
-
           args['dasharo_rom_file']=$1
           shift
         else
@@ -584,7 +726,6 @@ dcu_logo_parse_requirements() {
 
         # :flag.case_arg
         if [[ -n ${2+x} ]]; then
-
           args['--logo']="$2"
           shift
           shift
@@ -602,8 +743,8 @@ dcu_logo_parse_requirements() {
       *)
         # :command.parse_requirements_case
         # :command.parse_requirements_case_simple
+        # :argument.case
         if [[ -z ${args['dasharo_rom_file']+x} ]]; then
-
           args['dasharo_rom_file']=$1
           shift
         else
@@ -630,6 +771,111 @@ dcu_logo_parse_requirements() {
 
 }
 
+# :command.parse_requirements
+dcu_smmstore_parse_requirements() {
+  # :command.fixed_flags_filter
+  while [[ $# -gt 0 ]]; do
+    case "${1:-}" in
+      --help | -h)
+        long_usage=yes
+        dcu_smmstore_usage
+        exit
+        ;;
+
+      *)
+        break
+        ;;
+
+    esac
+  done
+
+  # :command.command_filter
+  action="smmstore"
+
+  # :command.parse_requirements_while
+  while [[ $# -gt 0 ]]; do
+    key="$1"
+    case "$key" in
+      # :flag.case
+      --get)
+
+        # :flag.case_arg
+        if [[ -n ${2+x} ]]; then
+          args['--get']="$2"
+          shift
+          shift
+        else
+          printf "%s\n" "--get requires an argument: --get VAR" >&2
+          exit 1
+        fi
+        ;;
+
+      # :flag.case
+      --list)
+
+        # :flag.case_no_arg
+        args['--list']=1
+        shift
+        ;;
+
+      # :flag.case
+      --set)
+
+        # :flag.case_arg
+        if [[ -n ${2+x} ]]; then
+          args['--set']="$2"
+          shift
+          shift
+        else
+          printf "%s\n" "--set requires an argument: --set VAR" >&2
+          exit 1
+        fi
+        ;;
+
+      # :flag.case
+      --value)
+
+        # :flag.case_arg
+        if [[ -n ${2+x} ]]; then
+          args['--value']="$2"
+          shift
+          shift
+        else
+          printf "%s\n" "--value requires an argument: --value VAL" >&2
+          exit 1
+        fi
+        ;;
+
+      -?*)
+        printf "invalid option: %s\n" "$key" >&2
+        exit 1
+        ;;
+
+      *)
+        # :command.parse_requirements_case
+        # :command.parse_requirements_case_simple
+        # :argument.case
+        if [[ -z ${args['dasharo_rom_file']+x} ]]; then
+          args['dasharo_rom_file']=$1
+          shift
+        else
+          printf "invalid argument: %s\n" "$key" >&2
+          exit 1
+        fi
+
+        ;;
+
+    esac
+  done
+
+  # :command.required_args_filter
+  if [[ -z ${args['dasharo_rom_file']+x} ]]; then
+    printf "missing required argument: DASHARO_ROM_FILE\nusage: dcu smmstore DASHARO_ROM_FILE [OPTIONS]\n" >&2
+    exit 1
+  fi
+
+}
+
 # :command.initialize
 initialize() {
   version="0.2.1"
@@ -642,6 +888,7 @@ initialize() {
   # SPDX-License-Identifier: Apache-2.0
 
   CBFSTOOL="cbfstool"
+  SMMSTORETOOL="smmstoretool"
 
 }
 
@@ -650,6 +897,7 @@ run() {
   declare -A args=()
   declare -A deps=()
   declare -a other_args=()
+  declare -a env_var_names=()
   declare -a input=()
   normalize_input "$@"
   parse_requirements "${input[@]}"
@@ -657,6 +905,7 @@ run() {
   case "$action" in
     "smbios") dcu_smbios_command ;;
     "logo") dcu_logo_command ;;
+    "smmstore") dcu_smmstore_command ;;
   esac
 }
 
