dcu: generated
Signed-off-by: Filip Gołaś <filip.golas@3mdeb.com>

diff --git a/dcu b/dcu
--- a/dcu
+++ b/dcu
@@ -353,8 +353,8 @@ dcu_mac_command() {
       fi
     fi
 
-    "${NVMTOOL}" "$GBE_FLASHREGION_FILENAME" setmac "${_mac}" || { echo "Failed to write MAC" ; return 21; }
-    "${IFDTOOL}" -i gbe:"$GBE_FLASHREGION_FILENAME" "${DASHARO_ROM}" || { echo "Failed to insert gbe to the binary" ; return 22; }
+    "${NVMTOOL}" "$GBE_FLASHREGION_FILENAME" setmac "${_mac}" || { echo "Failed to write MAC" ; return 22; }
+    "${IFDTOOL}" -i gbe:"$GBE_FLASHREGION_FILENAME" "${DASHARO_ROM}" || { echo "Failed to insert gbe to the binary" ; return 21; }
     echo "Moving ${DASHARO_ROM}.new to ${DASHARO_ROM}"
     mv "${DASHARO_ROM}.new" "${DASHARO_ROM}" -f
     echo "Success"
@@ -370,7 +370,7 @@ dcu_mac_command() {
     "${IFDTOOL}" -x "${DASHARO_ROM}" > /dev/null 2>&1 || { echo "Failed to extract sections"; }
     if [[ ! -f "$GBE_FLASHREGION_FILENAME" ]]; then
       echo "Managing the MAC address in this binary is currently not supported"
-      return 23
+      return 21
     fi
   }
 
