src/mac_command: Finish the command
Signed-off-by: Filip Gołaś <filip.golas@3mdeb.com>

diff --git a/dcu b/dcu
--- a/dcu
+++ b/dcu
@@ -1,5 +1,5 @@
 #!/usr/bin/env bash
-# This script was generated by bashly 1.1.10 (https://bashly.dannyb.co)
+# This script was generated by bashly 1.2.1 (https://bashly.dannyb.co)
 # Modifying it manually is not recommended
 
 # :wrapper.bash3_bouncer
@@ -17,15 +17,7 @@ version_command() {
 
 # :command.usage
 dcu_usage() {
-  if [[ -n $long_usage ]]; then
-    printf "dcu - Dasharo Configuration Utility\n"
-    echo
-
-  else
-    printf "dcu - Dasharo Configuration Utility\n"
-    echo
-
-  fi
+  printf "dcu - Dasharo Configuration Utility\n\n"
 
   printf "%s\n" "Usage:"
   printf "  dcu COMMAND\n"
@@ -34,6 +26,7 @@ dcu_usage() {
   echo
   # :command.usage_commands
   printf "%s\n" "Commands:"
+  printf "  %s   Get/set MAC adress in a firmare image\n" "mac     "
   printf "  %s   Edit SMBIOS data in a firmware image\n" "smbios  "
   printf "  %s   Insert custom logo boot splash into firmware image\n" "logo    "
   printf "  %s   Edit Dasharo configuration variables\n" "variable"
@@ -53,6 +46,7 @@ dcu_usage() {
 
     # :command.usage_examples
     printf "%s\n" "Examples:"
+    printf "  dcu setmac coreboot.rom 12:34:45:56:78:9A\n"
     printf "  dcu smbios coreboot.rom -u 96bcfa1a-42b4-6717-a44c-d8bbc18cbea4 -s D07229051\n"
     printf "  dcu logo coreboot.rom -l bootsplash.bmp\n"
     printf "  dcu variable coreboot.rom --get EnableWifiBt\n"
@@ -62,17 +56,51 @@ dcu_usage() {
 }
 
 # :command.usage
-dcu_smbios_usage() {
+dcu_mac_usage() {
+  printf "dcu mac - Get/set MAC adress in a firmare image\n\n"
+  printf "Alias: m\n"
+  echo
+
+  printf "%s\n" "Usage:"
+  printf "  dcu mac DASHARO_ROM_FILE [OPTIONS]\n"
+  printf "  dcu mac --help | -h\n"
+  echo
+
+  # :command.long_usage
   if [[ -n $long_usage ]]; then
-    printf "dcu smbios - Edit SMBIOS data in a firmware image\n"
+    printf "%s\n" "Options:"
+
+    # :command.usage_flags
+    # :flag.usage
+    printf "  %s\n" "--set, -s MAC"
+    printf "    Set mac address\n"
     echo
 
-  else
-    printf "dcu smbios - Edit SMBIOS data in a firmware image\n"
+    # :command.usage_fixed_flags
+    printf "  %s\n" "--help, -h"
+    printf "    Show this help\n"
+    echo
+
+    # :command.usage_args
+    printf "%s\n" "Arguments:"
+
+    # :argument.usage
+    printf "  %s\n" "DASHARO_ROM_FILE"
+    printf "    Dasharo firmware file (e.g. coreboot.rom)\n"
+    echo
+
+    # :command.usage_examples
+    printf "%s\n" "Examples:"
+    printf "  dcu mac coreboot.rom --set AB:CD:EF:01:23:45\n"
+    printf "  dcu mac coreboot.rom --get\n"
     echo
 
   fi
+}
 
+# :command.usage
+dcu_smbios_usage() {
+  printf "dcu smbios - Edit SMBIOS data in a firmware image\n\n"
   printf "Alias: s\n"
   echo
 
@@ -121,16 +149,7 @@ dcu_smbios_usage() {
 
 # :command.usage
 dcu_logo_usage() {
-  if [[ -n $long_usage ]]; then
-    printf "dcu logo - Insert custom logo boot splash into firmware image\n"
-    echo
-
-  else
-    printf "dcu logo - Insert custom logo boot splash into firmware image\n"
-    echo
-
-  fi
-
+  printf "dcu logo - Insert custom logo boot splash into firmware image\n\n"
   printf "Alias: l\n"
   echo
 
@@ -172,16 +191,7 @@ dcu_logo_usage() {
 
 # :command.usage
 dcu_variable_usage() {
-  if [[ -n $long_usage ]]; then
-    printf "dcu variable - Edit Dasharo configuration variables\n"
-    echo
-
-  else
-    printf "dcu variable - Edit Dasharo configuration variables\n"
-    echo
-
-  fi
-
+  printf "dcu variable - Edit Dasharo configuration variables\n\n"
   printf "Alias: v\n"
   echo
 
@@ -245,7 +255,7 @@ dcu_variable_usage() {
 # :command.normalize_input
 # :command.normalize_input_function
 normalize_input() {
-  local arg flags passthru
+  local arg passthru flags
   passthru=false
 
   while [[ $# -gt 0 ]]; do
@@ -315,6 +325,58 @@ inspect_args() {
 }
 
 # :command.command_functions
+# :command.function
+dcu_mac_command() {
+  # src/mac_command.sh
+  # SPDX-FileCopyrightText: 2023 3mdeb <contact@3mdeb.com>
+  #
+  # SPDX-License-Identifier: Apache-2.0
+
+  # inspect_args
+
+  DASHARO_ROM="${args[dasharo_rom_file]}"
+  MAC="${args[--set]}"
+
+  set_mac() {
+    local _mac="$1"
+
+    "${IFDTOOL}" -x "${DASHARO_ROM}" > /dev/null || { echo "Failed to extract sections" ; return 1; }
+    "${NVMTOOL}" "flashregion_3_gbe.bin" copy 0 || { echo "Failed to copy region 0 to region 1" ; return 1; }
+    "${NVMTOOL}" "flashregion_3_gbe.bin" setmac "${_mac}" || { echo "Failed to set MAC address" ; return 1; }
+    "${IFDTOOL}" -i gbe:flashregion_3_gbe.bin "${DASHARO_ROM}" || { echo "Failed to insert gbe to the binary" ; return 1; }
+    # echo "Moving ${DASHARO_ROM}.new to ${DASHARO_ROM}"
+    # mv "${DASHARO_ROM}.new" "${DASHARO_ROM}"
+    echo "Success"
+  }
+
+  get_mac() {
+    # dump sections
+    "${IFDTOOL}" -x "${DASHARO_ROM}" || { echo "Failed to extract sections" ; return 1; }
+    "${NVMTOOL}" "flashregion_3_gbe.bin" dump
+    echo "Success"
+  }
+
+  cleanup() {
+    rm -f flashregion*
+  }
+
+  if ! "${CBFSTOOL}" "${DASHARO_ROM}" extract -n config -r COREBOOT -f /tmp/cb_config > /dev/null 2> /dev/null; then
+    echo "Failed to extract coreboot configuration from the image"
+    exit 6
+  fi
+
+  echo "Will modify ${DASHARO_ROM}"
+
+  if [ -n "${MAC}" ]; then
+    set_mac "${MAC}"
+  else
+    get_mac
+  fi
+
+  cleanup
+
+}
+
 # :command.function
 dcu_smbios_command() {
   # src/smbios_command.sh
@@ -706,7 +768,7 @@ parse_requirements() {
     deps['cbfstool']="$(command -v cbfstool | head -n1)"
   else
     printf "missing dependency: cbfstool\n" >&2
-    printf "%s\n" "You can build one from source code:\n  https://github.com/Dasharo/dcu#compiling-cbfstool\nOr download and install pre-built version with following commands:\n  sudo wget -O /usr/local/bin/cbfstool https://dl.3mdeb.com/open-source-firmware/utilities/cbfstool\n  sudo chmod +x /usr/local/bin/cbfstool\n" >&2
+    printf "%s\n" "You can build one from source code: https://github.com/Dasharo/dcu#compiling-cbfstool or use DCU tool in container: https://github.com/Dasharo/dcu?tab=readme-ov-file#dasharo-configuration-container\n" >&2
     exit 1
   fi
 
@@ -730,7 +792,23 @@ parse_requirements() {
     deps['smmstoretool']="$(command -v smmstoretool | head -n1)"
   else
     printf "missing dependency: smmstoretool\n" >&2
-    printf "%s\n" "You can build one from source code:\n  https://github.com/Dasharo/dcu#compiling-smmstoretool\nOr download and install pre-built version with following commands:\n  sudo wget -O /usr/local/bin/smmstoretool https://dl.3mdeb.com/open-source-firmware/utilities/smmstoretool\n  sudo chmod +x /usr/local/bin/smmstoretool\n" >&2
+    printf "%s\n" "You can build one from source code: https://github.com/Dasharo/dcu#compiling-smmstoretool or use DCU tool in container: https://github.com/Dasharo/dcu?tab=readme-ov-file#dasharo-configuration-container\n" >&2
+    exit 1
+  fi
+
+  if command -v nvm >/dev/null 2>&1; then
+    deps['nvmtool']="$(command -v nvm | head -n1)"
+  else
+    printf "missing dependency: nvmtool\n" >&2
+    printf "%s\n" "You can build one from source code: https://github.com/Dasharo/dcu#compiling-nvmtool or use DCU tool in container: https://github.com/Dasharo/dcu?tab=readme-ov-file#dasharo-configuration-container\n" >&2
+    exit 1
+  fi
+
+  if command -v ifdtool >/dev/null 2>&1; then
+    deps['ifdtool']="$(command -v ifdtool | head -n1)"
+  else
+    printf "missing dependency: ifdtool\n" >&2
+    printf "%s\n" "You can build one from source code: https://github.com/Dasharo/dcu#compiling-ifdtool or use DCU tool in container: https://github.com/Dasharo/dcu?tab=readme-ov-file#dasharo-configuration-container\n" >&2
     exit 1
   fi
 
@@ -739,6 +817,13 @@ parse_requirements() {
 
   case $action in
     -*) ;;
+
+    mac | m)
+      action="mac"
+      shift
+      dcu_mac_parse_requirements "$@"
+      shift $#
+      ;;
 
     smbios | s)
       action="smbios"
@@ -794,6 +879,76 @@ parse_requirements() {
 
     esac
   done
+
+}
+
+# :command.parse_requirements
+dcu_mac_parse_requirements() {
+  # :command.fixed_flags_filter
+  while [[ $# -gt 0 ]]; do
+    case "${1:-}" in
+      --help | -h)
+        long_usage=yes
+        dcu_mac_usage
+        exit
+        ;;
+
+      *)
+        break
+        ;;
+
+    esac
+  done
+
+  # :command.command_filter
+  action="mac"
+
+  # :command.parse_requirements_while
+  while [[ $# -gt 0 ]]; do
+    key="$1"
+    case "$key" in
+      # :flag.case
+      --set | -s)
+
+        # :flag.case_arg
+        if [[ -n ${2+x} ]]; then
+          args['--set']="$2"
+          shift
+          shift
+        else
+          printf "%s\n" "--set requires an argument: --set, -s MAC" >&2
+          exit 1
+        fi
+        ;;
+
+      -?*)
+        printf "invalid option: %s\n" "$key" >&2
+        exit 1
+        ;;
+
+      *)
+        # :command.parse_requirements_case
+        # :command.parse_requirements_case_simple
+        # :argument.case
+        if [[ -z ${args['dasharo_rom_file']+x} ]]; then
+          args['dasharo_rom_file']=$1
+          shift
+        else
+          printf "invalid argument: %s\n" "$key" >&2
+          exit 1
+        fi
+
+        ;;
+
+    esac
+  done
+
+  # :command.required_args_filter
+  if [[ -z ${args['dasharo_rom_file']+x} ]]; then
+    printf "missing required argument: DASHARO_ROM_FILE\nusage: dcu mac DASHARO_ROM_FILE [OPTIONS]\n" >&2
+
+    exit 1
+  fi
 
 }
 
@@ -875,6 +1030,7 @@ dcu_smbios_parse_requirements() {
   # :command.required_args_filter
   if [[ -z ${args['dasharo_rom_file']+x} ]]; then
     printf "missing required argument: DASHARO_ROM_FILE\nusage: dcu smbios DASHARO_ROM_FILE [OPTIONS]\n" >&2
+
     exit 1
   fi
 
@@ -944,6 +1100,7 @@ dcu_logo_parse_requirements() {
   # :command.required_args_filter
   if [[ -z ${args['dasharo_rom_file']+x} ]]; then
     printf "missing required argument: DASHARO_ROM_FILE\nusage: dcu logo DASHARO_ROM_FILE [OPTIONS]\n" >&2
+
     exit 1
   fi
 
@@ -1063,6 +1220,7 @@ dcu_variable_parse_requirements() {
   # :command.required_args_filter
   if [[ -z ${args['dasharo_rom_file']+x} ]]; then
     printf "missing required argument: DASHARO_ROM_FILE\nusage: dcu variable DASHARO_ROM_FILE [OPTIONS]\n" >&2
+
     exit 1
   fi
 
@@ -1081,6 +1239,8 @@ initialize() {
 
   CBFSTOOL="cbfstool"
   SMMSTORETOOL="smmstoretool"
+  NVMTOOL="nvm"
+  IFDTOOL="ifdtool"
 
   error_exit() {
     _error_msg="$1"
@@ -1112,6 +1272,7 @@ run() {
   parse_requirements "${input[@]}"
 
   case "$action" in
+    "mac") dcu_mac_command ;;
     "smbios") dcu_smbios_command ;;
     "logo") dcu_logo_command ;;
     "variable") dcu_variable_command ;;
