src/mac_command.sh: Move common part to init function
Signed-off-by: Filip Gołaś <filip.golas@3mdeb.com>

diff --git a/dcu b/dcu
--- a/dcu
+++ b/dcu
@@ -336,17 +336,16 @@ dcu_mac_command() {
 
   DASHARO_ROM="${args[dasharo_rom_file]}"
   MAC="${args[--set]}"
+  GBE_FLASHREGION_FILENAME="flashregion_3_gbe.bin"
 
   set_mac() {
     local _mac="$1"
 
-    "${IFDTOOL}" -x "${DASHARO_ROM}" > /dev/null 2>&1 || { echo "Failed to extract sections" ; return 1; }
-
-    if "${NVMTOOL}" "flashregion_3_gbe.bin" copy 0; then
+    if "${NVMTOOL}" "$GBE_FLASHREGION_FILENAME" copy 0; then
       echo "Copying region 0 to region 1"
     else
       echo "Failed to copy region 0 to region 1"
-      if "${NVMTOOL}" "flashregion_3_gbe.bin" copy 1; then
+      if "${NVMTOOL}" "$GBE_FLASHREGION_FILENAME" copy 1; then
         echo "Copying region 1 to region 0"
       else
         echo "Failed to copy region 1 to region 0"
@@ -355,25 +354,35 @@ dcu_mac_command() {
       fi
     fi
 
-    "${NVMTOOL}" "flashregion_3_gbe.bin" setmac "${_mac}" || { echo "Failed to write MAC" ; return 1; }
-    "${IFDTOOL}" -i gbe:flashregion_3_gbe.bin "${DASHARO_ROM}" || { echo "Failed to insert gbe to the binary" ; return 1; }
+    "${NVMTOOL}" "$GBE_FLASHREGION_FILENAME" setmac "${_mac}" || { echo "Failed to write MAC" ; return 1; }
+    "${IFDTOOL}" -i gbe:"$GBE_FLASHREGION_FILENAME" "${DASHARO_ROM}" || { echo "Failed to insert gbe to the binary" ; return 1; }
     echo "Moving ${DASHARO_ROM}.new to ${DASHARO_ROM}"
-    mv "${DASHARO_ROM}.new" "${DASHARO_ROM}"
+    mv "${DASHARO_ROM}.new" "${DASHARO_ROM}" -f
     echo "Success"
   }
 
   get_mac() {
     # dump sections
     "${IFDTOOL}" -x "${DASHARO_ROM}" > /dev/null 2>&1 || { echo "Failed to extract sections" ; return 1; }
-    "${NVMTOOL}" "flashregion_3_gbe.bin" dump
+    "${NVMTOOL}" "$GBE_FLASHREGION_FILENAME" dump
     echo "Success"
+  }
+
+  init() {
+    "${IFDTOOL}" -x "${DASHARO_ROM}" > /dev/null 2>&1 || { echo "Failed to extract sections" ;}
+    if [[ ! -f "$GBE_FLASHREGION_FILENAME" ]]; then
+      echo "Managing the MAC address in this binary is currently not supported"
+      return 1
+    fi
   }
 
   cleanup() {
     rm -f flashregion*
   }
 
-  echo "Will modify ${DASHARO_ROM}"
+  echo "Using ${DASHARO_ROM}"
+
+  init
 
   if [ -n "${MAC}" ]; then
     set_mac "${MAC}"
