fix corner cases and add tests
Signed-off-by: Maciej Pijanowski <maciej.pijanowski@3mdeb.com>

diff --git a/dcu b/dcu
--- a/dcu
+++ b/dcu
@@ -1,5 +1,5 @@
 #!/usr/bin/env bash
-# This script was generated by bashly 1.1.10 (https://bashly.dannyb.co)
+# This script was generated by bashly 1.0.4 (https://bashly.dannyb.co)
 # Modifying it manually is not recommended
 
 # :wrapper.bash3_bouncer
@@ -237,16 +237,12 @@ dcu_variable_usage() {
 }
 
 # :command.normalize_input
-# :command.normalize_input_function
 normalize_input() {
-  local arg flags passthru
-  passthru=false
+  local arg flags
 
   while [[ $# -gt 0 ]]; do
     arg="$1"
-    if [[ $passthru == true ]]; then
-      input+=("$arg")
-    elif [[ $arg =~ ^(--[a-zA-Z0-9_\-]+)=(.+)$ ]]; then
+    if [[ $arg =~ ^(--[a-zA-Z0-9_\-]+)=(.+)$ ]]; then
       input+=("${BASH_REMATCH[1]}")
       input+=("${BASH_REMATCH[2]}")
     elif [[ $arg =~ ^(-[a-zA-Z0-9])=(.+)$ ]]; then
@@ -257,9 +253,6 @@ normalize_input() {
       for ((i = 0; i < ${#flags}; i++)); do
         input+=("-${flags:i:1}")
       done
-    elif [[ "$arg" == "--" ]]; then
-      passthru=true
-      input+=("$arg")
     else
       input+=("$arg")
     fi
@@ -267,15 +260,12 @@ normalize_input() {
     shift
   done
 }
-
 # :command.inspect_args
 inspect_args() {
   if ((${#args[@]})); then
     readarray -t sorted_keys < <(printf '%s\n' "${!args[@]}" | sort)
     echo args:
-    for k in "${sorted_keys[@]}"; do
-      echo "- \${args[$k]} = ${args[$k]}"
-    done
+    for k in "${sorted_keys[@]}"; do echo "- \${args[$k]} = ${args[$k]}"; done
   else
     echo args: none
   fi
@@ -293,19 +283,9 @@ inspect_args() {
     readarray -t sorted_keys < <(printf '%s\n' "${!deps[@]}" | sort)
     echo
     echo deps:
-    for k in "${sorted_keys[@]}"; do
-      echo "- \${deps[$k]} = ${deps[$k]}"
-    done
+    for k in "${sorted_keys[@]}"; do echo "- \${deps[$k]} = ${deps[$k]}"; done
   fi
 
-  if ((${#env_var_names[@]})); then
-    readarray -t sorted_names < <(printf '%s\n' "${env_var_names[@]}" | sort)
-    echo
-    echo "environment variables:"
-    for k in "${sorted_names[@]}"; do
-      echo "- \$$k = ${!k:-}"
-    done
-  fi
 }
 
 # :command.command_functions
@@ -466,7 +446,7 @@ dcu_variable_command() {
 
   typeof()
   {
-    # TODO: determine type programatically
+    # TODO: determine type programmatically
     case $1 in
       LockBios \
       |NetworkBoot \
@@ -498,36 +478,46 @@ dcu_variable_command() {
   {
     case `typeof $1` in
       bool)
-        if [ `${SMMSTORETOOL} ${DASHARO_ROM} get -g dasharo -n $1 -t bool` = "false" ]; then
+        _result="$(${SMMSTORETOOL} ${DASHARO_ROM} get -g dasharo -n $1 -t bool)"
+        error_check "Variable store was not initialized yet. You need to set some variable first via --set option." 17
+        if [ "${_result}" = "false" ]; then
           echo "Disabled"
-        elif [ `${SMMSTORETOOL} ${DASHARO_ROM} get -g dasharo -n $1 -t bool` = "true" ]; then
+        elif [ "${_result}" = "true" ]; then
           echo "Enabled"
         else
           echo "Error!"
-          exit 1
+          exit 18
         fi
         ;;
       memode)
-        if [ `${SMMSTORETOOL} ${DASHARO_ROM} get -g dasharo -n $1 -t uint8` = "0" ]; then
+        _result="$(${SMMSTORETOOL} ${DASHARO_ROM} get -g dasharo -n $1 -t uint8)"
+        error_check "Variable store was not initialized yet. You need to set some variable first via --set option." 17
+        if [ "${_result}" = "0" ]; then
           echo "Enabled"
-        elif [ `${SMMSTORETOOL} ${DASHARO_ROM} get -g dasharo -n $1 -t uint8` = "1" ]; then
+        elif [ "${_result}" = "1" ]; then
           echo "DisabledSoft"
-        elif [ `${SMMSTORETOOL} ${DASHARO_ROM} get -g dasharo -n $1 -t uint8` = "2" ]; then
+        elif [ "${_result}" = "2" ]; then
           echo "DisabledHAP"
         else
           echo "Error!"
-          exit 1
+          exit 18
         fi
         ;;
       fancurve)
-        if [ `${SMMSTORETOOL} ${DASHARO_ROM} get -g dasharo -n $1 -t uint8` = "0" ]; then
+        _result="$(${SMMSTORETOOL} ${DASHARO_ROM} get -g dasharo -n $1 -t uint8)"
+        error_check "Variable store was not initialized yet. You need to set some variable first via --set option." 17
+        if [ "${_result}" = "0" ]; then
           echo "Silent"
-        elif [ `${SMMSTORETOOL} ${DASHARO_ROM} get -g dasharo -n $1 -t uint8` = "1" ]; then
+        elif [ "${_result}" = "1" ]; then
           echo "Performance"
         else
           echo "Error!"
-          exit 1
+          exit 18
         fi
+        ;;
+      *)
+        echo "Variable \"${1}\" is not supported by the DCU tool yet".
+        exit 20
         ;;
     esac
   }
@@ -551,7 +541,7 @@ dcu_variable_command() {
 
   get_variable()
   {
-    echo $(valueof ${GET})
+    echo "$(valueof ${GET})"
   }
 
   set_variable()
@@ -561,23 +551,29 @@ dcu_variable_command() {
       echo "Value to set not provided, exiting" >&2
       exit 1
     fi
-    if [ -z "$(acceptedvaluesfor ${SET})" ]; then
-      echo "Setting ${SET} is not supported"
-      exit 1
+
+    _accepted_values="$(acceptedvaluesfor ${SET})"
+    _accepted_values_split=$(echo ${_accepted_values} | sed "s/\///g")
+    _accepted_values_count=$(echo ${_accepted_values_split} | wc -w)
+
+    if [ -z "${_accepted_values}" ]; then
+      echo "Variable \"${SET}\" is not supported by the DCU tool yet".
+      exit 20
     fi
     i=0
-    for a in $(acceptedvaluesfor ${SET} | sed "s/\///g"); do
+    for a in ${_accepted_values_split} ; do
       if [ $a = ${VALUE} ]; then
         break
       fi
       i=$(($i + 1))
     done
-    if [ ${i} -ge $(echo acceptedvaluesfor ${SET} | sed "s/\///g" | wc -w) ]; then
-      echo "Value ${VALUE} is out of range (expected one of: $(acceptedvaluesfor ${SET}))"
+    if [ ${i} -ge ${_accepted_values_count} ]; then
+      echo "Value ${VALUE} is out of range (expected one of: ${_accepted_values})"
       exit 1
     fi
 
     ${SMMSTORETOOL} ${DASHARO_ROM} set -g dasharo -n ${SET} -t uint8 -v ${i}
+    echo "Successfully set variable ${SET} in the variable store."
   }
 
   list_variables()
@@ -601,7 +597,6 @@ dcu_variable_command() {
           ;;
       esac
     done
-
   }
 
   if [ -n "${GET}" ]
@@ -645,7 +640,12 @@ parse_requirements() {
     deps['cbfstool']="$(command -v cbfstool | head -n1)"
   else
     printf "missing dependency: cbfstool\n" >&2
-    printf "%s\n" "You can build one from source code:\n  https://github.com/Dasharo/dcu#compiling-cbfstool\nOr download and install pre-built version with following commands:\n  sudo wget -O /usr/local/bin/cbfstool https://dl.3mdeb.com/open-source-firmware/utilities/cbfstool\n  sudo chmod +x /usr/local/bin/cbfstool\n" >&2
+    printf "%s\n" "You can build one from source code:
+    https://github.com/Dasharo/dcu#compiling-cbfstool
+  Or download and install pre-built version with following commands:
+    sudo wget -O /usr/local/bin/cbfstool https://dl.3mdeb.com/open-source-firmware/utilities/cbfstool
+    sudo chmod +x /usr/local/bin/cbfstool
+  " >&2
     exit 1
   fi
 
@@ -669,7 +669,12 @@ parse_requirements() {
     deps['smmstoretool']="$(command -v smmstoretool | head -n1)"
   else
     printf "missing dependency: smmstoretool\n" >&2
-    printf "%s\n" "You can build one from source code:\n  https://github.com/Dasharo/dcu#compiling-smmstoretool\nOr download and install pre-built version with following commands:\n  sudo wget -O /usr/local/bin/smmstoretool https://dl.3mdeb.com/open-source-firmware/utilities/smmstoretool\n  sudo chmod +x /usr/local/bin/smmstoretool\n" >&2
+    printf "%s\n" "You can build one from source code:
+    https://github.com/Dasharo/dcu#compiling-smmstoretool
+  Or download and install pre-built version with following commands:
+    sudo wget -O /usr/local/bin/smmstoretool https://dl.3mdeb.com/open-source-firmware/utilities/smmstoretool
+    sudo chmod +x /usr/local/bin/smmstoretool
+  " >&2
     exit 1
   fi
 
@@ -766,6 +771,7 @@ dcu_smbios_parse_requirements() {
 
         # :flag.case_arg
         if [[ -n ${2+x} ]]; then
+
           args['--uuid']="$2"
           shift
           shift
@@ -780,6 +786,7 @@ dcu_smbios_parse_requirements() {
 
         # :flag.case_arg
         if [[ -n ${2+x} ]]; then
+
           args['--serial-number']="$2"
           shift
           shift
@@ -797,8 +804,8 @@ dcu_smbios_parse_requirements() {
       *)
         # :command.parse_requirements_case
         # :command.parse_requirements_case_simple
-        # :argument.case
         if [[ -z ${args['dasharo_rom_file']+x} ]]; then
+
           args['dasharo_rom_file']=$1
           shift
         else
@@ -849,6 +856,7 @@ dcu_logo_parse_requirements() {
 
         # :flag.case_arg
         if [[ -n ${2+x} ]]; then
+
           args['--logo']="$2"
           shift
           shift
@@ -866,8 +874,8 @@ dcu_logo_parse_requirements() {
       *)
         # :command.parse_requirements_case
         # :command.parse_requirements_case_simple
-        # :argument.case
         if [[ -z ${args['dasharo_rom_file']+x} ]]; then
+
           args['dasharo_rom_file']=$1
           shift
         else
@@ -924,6 +932,7 @@ dcu_variable_parse_requirements() {
 
         # :flag.case_arg
         if [[ -n ${2+x} ]]; then
+
           args['--get']="$2"
           shift
           shift
@@ -946,6 +955,7 @@ dcu_variable_parse_requirements() {
 
         # :flag.case_arg
         if [[ -n ${2+x} ]]; then
+
           args['--set']="$2"
           shift
           shift
@@ -960,6 +970,7 @@ dcu_variable_parse_requirements() {
 
         # :flag.case_arg
         if [[ -n ${2+x} ]]; then
+
           args['--value']="$2"
           shift
           shift
@@ -977,8 +988,8 @@ dcu_variable_parse_requirements() {
       *)
         # :command.parse_requirements_case
         # :command.parse_requirements_case_simple
-        # :argument.case
         if [[ -z ${args['dasharo_rom_file']+x} ]]; then
+
           args['dasharo_rom_file']=$1
           shift
         else
@@ -1013,6 +1024,23 @@ initialize() {
   CBFSTOOL="cbfstool"
   SMMSTORETOOL="smmstoretool"
 
+  error_exit() {
+    _error_msg="$1"
+    _exit_code="$2"
+    if [ -n "$_error_msg" ]; then
+      # Avoid printing empty line if no message was passed
+      echo "$_error_msg"
+    fi
+    exit ${_exit_code}
+  }
+
+  error_check() {
+    _error_code=$?
+    _error_msg="$1"
+    _exit_code="$2"
+    [ $_error_code -ne 0 ] && error_exit "$_error_msg (error code: $_error_code)" ${_exit_code}
+  }
+
 }
 
 # :command.run
@@ -1020,7 +1048,6 @@ run() {
   declare -A args=()
   declare -A deps=()
   declare -a other_args=()
-  declare -a env_var_names=()
   declare -a input=()
   normalize_input "$@"
   parse_requirements "${input[@]}"
